### ISSUE TITLE
Added 2 new users successfully, adding 3rd results in fail. Cannot add any more users.

### ISSUE THREAD

**Issue by dan-langridge** [VauxhallFoodbank/vauxhall-foodbank#374] opened 2024-06-15 13:22 UTC
### Reproduction steps

Tried adding users, after 2 successful users added, the 3rd user failed

Error code:
Failed to invite the new user. Please try again later. Log ID: 6fd4af97-5569-45a6-b371-d7a8a56a9fa8

Tried pressing “Invite User” again with pre-filled data from 1st attempt which stayed filled in, 2nd attempt failed.
Waited 2 minutes - failed again

Error code:
Failed to invite the new user. Please try again later. Log ID: eca7d91c-4170-4586-9466-bd64356364fe

Refreshed page. Tried adding a different user with different details, failed again.

Waited 10 minutes, still failed.

Waited another 30 minutes - successfully added 1 more user.
After this successful attempt, tried adding another used and it failed again to add the new user.

### Expected behaviour

I would hope that I could add as many users as I want in succession without having to wait a time between adding users.
When we go live i need to add 50+ users.

### What browsers are you seeing the problem on?

Safari

### What OS is your computer running on?

macOS

**Comment by stonelink** [comment] 2024-07-23 21:19
When pickiing this up, see also https://softwiretech.atlassian.net/browse/VFB-300

**Comment by stonelink** [comment] 2024-08-18 13:07
Hi @dan-langridge,
From the discussion in last week's demo, I believe this is ready for your UAT.

**Comment by Stuart-Knowles-SW** [comment] 2024-08-27 10:51
Moving this back to ready, since I don't actually believe this was fixed as we thought it was. I think the problem is that [supabase's email client is not supposed to be used in production](https://supabase.com/docs/guides/auth/auth-smtp) or test environments and has a rate limit of 3 emails per hour.

The solution is to spin up our own email server on AWS and connect it to supabase. This process is described between the docs linked above (for the supabase side of things) and [here](https://docs.aws.amazon.com/ses/latest/dg/send-email-smtp.html) for the AWS side. It shouldn't be too arduous but will need an experienced developer with AWS access.

**Comment by stonelink** [comment] 2024-09-16 20:30
Setting up the email server in AWS SES is https://softwiretech.atlassian.net/browse/VFB-358

**Comment by stonelink** [comment] 2024-09-29 16:38
As noted on VFB-358, after setting up SES and attaching to the Dev environment, I tested sending 6 invite emails in succession - all of which worked.
SES is no longer in the sandbox and has been tested sending to unverified identities.
As part of the next release, the Staging environment will be hooked up to SES.

**Comment by dan-langridge** [comment] 2024-11-07 15:42
this is working.
added 11 users consecutively and all emails arrived to my inbox
happy that this is complete

**Closed as completed** 2024-11-07 15:45 UTC
Labels: bug
